[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0-py3-none-any.whl",
  "python download_nltk_data.py"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
